### ISSUE TITLE
Remove .html extension

### ISSUE THREAD

**Issue by serisman** [free-pdk/free-pdk.github.io#10]
Might be nice to remove the .html extensions (like most newer websites are doing).

It already seems to work in the browser, but Jekyll probably needs a configuration change to truly support this:
https://medium.com/@mittalyashu/how-to-remove-html-extension-in-jekyll-efeb48bd725f

**Comment by cpldcpu** [comment]
Addressed by https://github.com/free-pdk/free-pdk.github.io/pull/13
