### ISSUE TITLE
Add link to datasheets

### ISSUE THREAD

**Issue by serisman** [free-pdk/free-pdk.github.io#11]
How do we feel about adding a link to the datasheet for each IC?

If so, should it be a direct link to the .PDF hosted on Padauk's website (i.e. http://www.padauk.com.tw/upload/doc/PFS173%20datasheet_v105_EN_20200619.pdf), or would we be able to re-host them and link directly?

I could see the link going on the chip's 'detail' page under the 'Official Product Page' link, and also maybe as an icon on the primary page next to all the badges (hopefully to be converted to a table soon).

**Comment by cmfcmf** [comment]
My main concern with directly linking data sheets is that we then possibly link to an outdated version after Padauk updates the datasheet.

**Comment by cpldcpu** [comment]
Indeed. Deep links bear the risk of quick expiration and it is also a somewhat marginal practice.

We could link to the product pages instead? They seem to use a fixed URL.

e.g.
http://www.padauk.com.tw/en/product/show.aspx?num=114

**Comment by cpldcpu** [comment]
Links to the Padauk homepage are now implemented.
