### ISSUE TITLE
Add support for PMS171B

### ISSUE THREAD

**Issue by serisman** [free-pdk/free-pdk.github.io#16]
PMS171B has easy-pdk-programmer-software support in the development branch.

We should add it to the website as well and make sure we have specs and pinouts available.

**Comment by serisman** [comment]
@cpldcpu - you can assign me to this if you want.  It looks like I can't assign myself.

**Comment by serisman** [comment]
PR created: https://github.com/free-pdk/free-pdk.github.io/pull/17

I still need to go create pinouts for this.

**Comment by cpldcpu** [comment]
merged

**Comment by serisman** [comment]
Pinouts should be available once 'upstream' PR gets merged: https://github.com/cmfcmf/ic-pinout-diagram-generator/pull/9
