### ISSUE TITLE
There is no such thing as PMS15A

### ISSUE THREAD

**Issue by freepdk** [free-pdk/free-pdk.github.io#21]
I have some PMS15A and when you read them out you can see that infact they are PMS150C (same hardware ID, amount of program memory is same, ...)

PMS15A is just a marketing name of PMS150C. Inside the IC is the exact same silicon. Not a single difference.

Only the PADAUK IDE is limiting the amount of code you can use in case you choose PMS15A. If you choose PMS150C then you can use the complete code memory (1K). Also original PADAUK WRITER happily writes the PMS150C code to a "PMS15A"... and of course, everything is working.

**Comment by cpldcpu** [comment]
So you want to remove the device? However, if it actually is on the market, people will ask for it, regardless whether its the same as another type or not.

**Comment by cpldcpu** [comment]
Btw, I also had this thought when I first saw the device. Since they don't even have identifying information on their packages, they could just relabel their reels.

**Comment by serisman** [comment]
We could have a 'notes' section at the top of the 'detail' page for the PMS15A explaining what @freepdk mentioned.
We could also modify the table for the PMS15A to just show a similar note instead of all the normal columns... or put an asterisk by the name with a note below the table.

Are we sure that Padauk won't introduce actual changes for the PMS15A in the future, or start shipping IC with potentially bad OTP memory in the upper half?

**Comment by cpldcpu** [comment]
The notes section is a good idea. This could also be used to add information about other topics.

**Comment by freepdk** [comment]
I also would do it like the data sheet and add is as a variant/ marketing name of the PMS150C in a "notes" section.

**Comment by cmfcmf** [comment]
I added a note in #31. Let me know what you think. Preview: https://deploy-preview-31--free-pdk-preview.netlify.app/

**Comment by freepdk** [comment]
@cmfcmf 
The note is good, but it destroys your beautiful table. 

How about showing ROM size as:
 0.5 KW 
 (1 KW*)

And when you hover or click on the (1KW) then popup / tool tip shows the note ?

I also would place the row next to PMS150C (above or below).

:-)

**Comment by cmfcmf** [comment]
> I also would place the row next to PMS150C (above or below).

done!

> The note is good, but it destroys your beautiful table.
> And when you hover or click on the (1KW) then popup / tool tip shows the note ?

Hmm, I tend to like the current design with the extra table row. I feel like using a tooltip or popup is unnecessarily complicated (and would require JavaScript if we want to still have a clickable link to the "Source")

**Comment by cpldcpu** [comment]
I have to agree with this. Adding a line also overstates the importance of
the information.

Claiming that the device does indeed have more memory is dangerous, as this
could be changed at any time.

I would just add a line on the detail page with the pinout.


freepdk <notifications@github.com> schrieb am So., 12. Juli 2020, 10:14:

**Comment by cmfcmf** [comment]
Alright, take another look at the preview 👍

**Comment by cpldcpu** [comment]
Looks good! 👍

**Comment by freepdk** [comment]
Looks great :-)
