### ISSUE TITLE
Use netlify for PR previews

### ISSUE THREAD

**Issue by cmfcmf** [free-pdk/free-pdk.github.io#28]
I would like to setup netlify for PR previews like discussed in https://github.com/free-pdk/free-pdk.github.io/pull/3

To do that, netlify needs read access to this repository, but a repository admin first needs to approve that (you should've recevied an email).

**Comment by cpldcpu** [comment]
Done.

Btw, I tried it before with no success, but you have a much better grasp, so I guess you'll get it to work :)

**Comment by cpldcpu** [comment]
You should have admin access to this repository now via the team I just set up.
