### ISSUE TITLE
Drop development branch

### ISSUE THREAD

**Issue by cmfcmf** [free-pdk/free-pdk.github.io#32]
I don't think we necessarily need both a development and production branch. It adds an extra step of unnecessary complexity and it also breaks the GitHub Action that refreshes the community projects once per day, [which always deploys the default (= development) branch](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events). This is why some changes from the development branch are already live at free-pdk.github.io, even though development has not yet been merged into production.

I would therefore like to delete the production branch and rename the development branch to production. Would that be okay with you?

**Comment by cpldcpu** [comment]
It seems that Netlify will also build previews from all pull requests, right? In that case the development branch could be dropped indeed. I only introduced it to simplify testing of multiple changes.

**Comment by cmfcmf** [comment]
> It seems that Netlify will also build previews from all pull requests, right?

yes :+1: 

> I only introduced it to simplify testing of multiple changes.

I see! Thank you for the explanation.
