### ISSUE TITLE
Sorry for hickup with merges

### ISSUE THREAD

**Issue by cpldcpu** [free-pdk/free-pdk.github.io#38]
Sorry, the github plugin for VSCODE introduced a very confusing unintential merge when I tried to pull the latestest production branch:

![grafik](https://user-images.githubusercontent.com/4086406/87453740-4438dc00-c603-11ea-89db-b1500de1fcb0.png)

I tried to roll it back but noticed that this actually reverted to an older version, so I reverted the reversion.

Looking into whats going on, I hope the current state is the right one.

**Comment by cmfcmf** [comment]
Maybe this setting fixes it in the future: https://code.visualstudio.com/updates/v1_28#_always-rebase-when-running-sync

**Comment by cpldcpu** [comment]
That's a good idea, indeed. I am still quite confused how this happened. It seems like the head was merged into a minor change of mine after rebasing everything to the state of my repository.
