### ISSUE TITLE
Detect Padauk projects that were created with the official IDE and add a note in the project list

### ISSUE THREAD

**Issue by cpldcpu** [free-pdk/free-pdk.github.io#39]
Projects created with the official IDE can be recognized by looking for the *.PRJ or *.PRE extension in the repository. There may be a few false positives, so it would be advisable not to use this classifier to segregate files. Instead, a note could be added instead.

One alternative proposal could be to ask to add the topic "Free-PDK" to the repositority if the project is based on the OSS tool-chain and feature those repositories, for example by prioritizing them in the order or by adding flair or similar layout elements.

**Comment by cpldcpu** [comment]
Maybe the latter is a better idea. This could also be limited to project that are based on the new version of includes etc...

**Comment by cmfcmf** [comment]
I think we should combine both methods. I suggest the following algorithm:

1. Search for repos with the `padauk` topic that are not on our manually curated exclusion list. 
2. If it has the `free-pdk` topic, mark it as "free pdk toolchain". If it has a `.PRE` file, mark it as "proprietary toolchain". If it has neither the `free-pdk` topic, nor a `.PRE` file, also mark it as "free pdk toolchain".


> that are based on the new version of includes etc...

I don't think this is feasible. After all, we don't and can't control which topics users add to their repositories. Asking people to add topics based on the version of the free pdk toolchain they are using seems a bit over the top. IMHO we also shouldn't put _too_ much thought into the community projects section. I see it as a list of interesting projects that may be worth checking out when you are interested in Padauk mikrocontrollers, not as the definitive list of example projects that work with the newest toolchain. Having said that, we should probably extend the explanatory comment at the top of the community projects section to explicitly state that not all projects listed below may be compatible with the free pdk toolchain.

**Comment by cpldcpu** [comment]
Your proposal sounds good!

Yes, we cannot expect people to add topics reflecting specific versioning of tools and includes they use. I was rather thinking about a topic that would emphasize that the project is based on the recentely refactored includes. People could add it to specifically promote their project. It should be in the interest of the organization to specifically promote projects that are based  up to date. But that goal can alrady be achieved with the "free-pdk" topic/tag.
