### ISSUE TITLE
Not all repositories showing up in search results

### ISSUE THREAD

**Issue by cpldcpu** [free-pdk/free-pdk.github.io#45]
I recently created a new repository for an (old) project, which I had not published in a dedicated repository yet.

https://github.com/cpldcpu/Addressable_7-Segment

Interestingly it is not showing up on the free-pdk page. The reason for that is that it is not showing up in the Github search results despite having the topic "padauk". I suspect that there is some kind of metric that excludes too new repositories or repositories that look like forks.

Curious indeed. I wonder what is triggering this.

**Comment by cmfcmf** [comment]
Maybe asking GitHub Support would be worth a shot?

**Comment by cpldcpu** [comment]
Ok, I figured out the issue: I had no files in the repository that counted as "code", only EDA files. It seems that Githubs scoffs at lowly hardware projects and your repository will only show up in the search results once you added real code.

I added the firmware now and everything is fine.
