### ISSUE TITLE
PFS122 not showing up

### ISSUE THREAD

**Issue by spth** [free-pdk/free-pdk.github.io#46]
I updated https://github.com/free-pdk/fppa-pdk-documentation/blob/master/PADAUK_FPPA_14_bit_instruction_set.wikitext; how do I get the new data to show up at https://free-pdk.github.io/instruction-sets/PDK14?

**Comment by cpldcpu** [comment]
It will update automatically once a day via github action.

Btw - the PFS122 is a funny device. It's not anywhere on their roadmaps? Basically it's just a PFS172 with a different ADC?

**Comment by cpldcpu** [comment]
it's there now.
